---
title: "analysis of solar panel data"
author: "Hannes Schoss"
output:
  pdf_document:
    toc: true
    number_sections: true
geometry: margin=1.5cm
header-includes:
  - \usepackage{booktabs}
  - \usepackage{float}
  - \usepackage{placeins}
---

There is two ways to become more cost efficient.
One small lever is to cut down on grid consumption and save a small amount per season
roughly this is about x EUR per year in energy costs.

A considerably bigger lever is to use up the energy yourself and feed as little 
energy as possible in the grid.

should show a line with the 80% confidence interval for each of the six summer months



# solar production over the day

i want the time data over one day with 80 % CI's for summer and winter each

i want the 
I want more detailled data. More precise data over the course of a day. 

Right now i used the sonnen api, but i need the solaredge.com API




ithere is a battery called battery state of charge. I want a new variable called
first_full_battery that marks the time this batttery is full for the first time in the day








the timespan to this hour should be a grey area in the graphic

'data.frame':	9356 obs. of  15 variables:
 $ production             : int  6802 6063 1737 4 0 0 0 873 2278 2297 ...
 $ consumption            : int  1010 906 756 972 677 346 301 332 879 1333 ...
 $ battery_charge         : int  4022 111 74 0 0 0 0 689 1433 1086 ...
 $ battery_discharge      : int  21 1 10 931 644 313 269 134 48 221 ...
 $ grid_feedin            : int  1819 5047 926 7 2 1 1 20 36 202 ...
 $ grid_consumption       : int  31 0 7 43 36 32 32 35 23 101 ...
 $ battery_state_of_charge: int  66 100 99 85 57 40 29 21 55 87 ...
 $ direct_consumption     : int  987 906 743 4 0 0 0 180 828 1104 ...
 $ time                   : POSIXct, format: "2023-03-11 09:00:00" "2023-03-11 12:00:00" ...
 $ year                   : int  2023 2023 2023 2023 2023 2023 2023 2023 2023 2023 ...
 $ month                  : int  3 3 3 3 3 3 3 3 3 3 ...
 $ day                    : int  11 11 11 11 11 12 12 12 12 12 ...
 $ hour                   : int  9 12 15 18 21 0 3 6 9 12 ...
 $ date                   : Date, format: "2023-03-11" "2023-03-11" ...
 $ season                 : chr  "cold" "cold" "cold" "cold" ...
>



ci_fun <- function(x) {
  n <- sum(!is.na(x))
  m <- mean(x, na.rm = TRUE)
  e <- qt(0.90, df = n - 1) * sd(x, na.rm = TRUE) / sqrt(n)

  c(mean = m, lower = m - e, upper = m + e)
}

prod_hour_month <- aggregate(
  production ~ month + hour,
  dat[dat$season == "warm" & dat$hour >= 6 & dat$hour <= 21, ],
  mean,
  na.rm = TRUE
)

prod_hour_warm <- aggregate(
  production ~ hour,
  dat[dat$season == "warm" & dat$hour >= 6 & dat$hour <= 21, ],
  ci_fun
)

prod_hour_warm <- do.call(data.frame, prod_hour_warm)
names(prod_hour_warm) <- c("hour", "mean", "lower", "upper")

plot(
  NA,
  xlim = c(6, 21),
  ylim = range(
    c(prod_hour_warm$lower, prod_hour_warm$upper,
      prod_hour_month$production),
    na.rm = TRUE
  ),
  xlab = "Hour of day",
  ylab = "Solar production",
  xaxt = "n",
  type = "n"
)

axis(
  1,
  at = c(6, 9, 12, 15, 18, 21),
  labels = c("06:00", "09:00", "12:00", "15:00", "18:00", "21:00")
)

polygon(
  c(prod_hour_warm$hour, rev(prod_hour_warm$hour)),
  c(prod_hour_warm$lower, rev(prod_hour_warm$upper)),
  col = rgb(0, 0, 0, 0.08),
  border = NA
)

lines(
  prod_hour_warm$hour,
  prod_hour_warm$mean,
  lwd = 3,
  col = rgb(0, 0, 0, 0.35)
)

warm_months <- sort(unique(prod_hour_month$month))

for (i in seq_along(warm_months)) {
  tmp <- prod_hour_month[prod_hour_month$month == warm_months[i], ]

  lines(
    tmp$hour,
    tmp$production,
    lwd = 2,
    col = i
  )
}

legend(
  "topright",
  legend = month.abb[warm_months],
  col = seq_along(warm_months),
  lty = 1,
  lwd = 2,
  title = "Month"
)



## grid consumption during the night

plot(production ~ hour, dat[dat$season == "warm", ])


I want another graphic for plotting the grid_consumption and i want it to start
at 21:00 Uhr and go through the night till the morning at 06:00. I aslo want
you to write the version below more concise (e.g. no extra dataframe for
warm_dat)




warm_dat <- dat[dat$season == "warm", ]

prod_hour_month <- aggregate(
  production ~ month + hour,
  data = warm_dat,
  FUN = function(x) {
    n <- sum(!is.na(x))
    m <- mean(x, na.rm = TRUE)
    s <- sd(x, na.rm = TRUE)

    error <- qt(0.90, df = n - 1) * s / sqrt(n)

    c(
      mean = m,
      lower = m - error,
      upper = m + error
    )
  }
)

prod_hour_month <- do.call(
  data.frame,
  prod_hour_month
)

names(prod_hour_month) <- c(
  "month",
  "hour",
  "mean",
  "lower",
  "upper"
)

prod_hour_month <- prod_hour_month[
  order(prod_hour_month$month, prod_hour_month$hour),
]

plot(
  NA,
  xlim = c(6, 24),
  ylim = range(
    c(prod_hour_month$lower, prod_hour_month$upper),
    na.rm = TRUE
  ),
  xlab = "Hour of day",
  ylab = "Production",
  xaxt = "n",
  type = "n"
)

axis(
  side = 1,
  at = c(6, 9, 12, 15, 18, 21),
  labels = c("06:00", "09:00", "12:00", "15:00",
             "18:00", "21:00")
)

warm_months <- sort(unique(prod_hour_month$month))

for (i in seq_along(warm_months)) {
  month_i <- warm_months[i]
  tmp <- prod_hour_month[prod_hour_month$month == month_i, ]

  lines(
    tmp$hour,
    tmp$mean,
    type = "l",
    lwd = 2,
    col = i
  )

  lines(
    tmp$hour,
    tmp$lower,
    type = "l",
    lty = 2,
    col = i
  )

  lines(
    tmp$hour,
    tmp$upper,
    type = "l",
    lty = 2,
    col = i
  )
}

legend(
  "topright",
  legend = month.abb[warm_months],
  col = seq_along(warm_months),
  lty = 1,
  lwd = 2,
  title = "Month"
)






9. Statistical and machine-learning appendix

I would not put this too early. Use it after the main story, as a deeper analytical layer.

Core questions from your list


Which variables explain the largest share of variance in household grid consumption?


Can days be grouped into typical usage patterns using clustering methods?
Can a machine learning model predict the next day’s energy production based on the previous day’s data?
Can daily grid consumption be predicted from solar production, household consumption, and battery behavior?
Is there a statistically significant weekday/weekend difference in solar production?
Is there a statistically significant weekday/weekend difference in household consumption?


